sudo: false

language: php

notifications:
  email: false

cache:
  directories:
    - vendor

matrix:
  include:
    - php: 7.0
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=trunk
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=latest

before_script:
  - composer install --prefer-source
  - mkdir -p build/logs
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - ./vendor/bin/phpunit
  - WP_MULTISITE=1 ./vendor/bin/phpunit
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - if [ $CODECLIMATE_REPO_TOKEN ]; then ./vendor/bin/test-reporter; fi;
